name: ml-env
channels:
 - conda-forge
 - defaults
 - pytorch
dependencies:
 - python=3.9
 - pandas
 - xarray
 - xesmf
 - dask
 - netCDF4
 - bottleneck
 - scikit-learn
 - pytorch::pytorch
 - pytorch::torchvision
 - pytorch::torchaudio
